<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Scalar.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Clean.Architecture.Domain\Clean.Architecture.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\" />
  </ItemGroup>

</Project>
